### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by james2432**
Added french translation.

Some cases are very context sensitive (e.g. the "between" in french(entre) sometimes needs a "le" after it and sometimes doesn't depending on context)

There is no french translation for Ordinal, so made my own(it's very simple in french)

### CODE REVIEW

**Comment by plepe** [comment]
Thanks :-) It's already online on OpenStreetBrowser.

Do you think my approach is too simplistic?

**Comment by james2432** [comment]
I mean best would be something like transifex, but then I got to thinking that's not going to work because of context and each language has different rules. It's simple enough someone can pick it up within a couple of minutes without all the intricacies of the language

**Comment by plepe** [comment]
I re-designed the templates, I think they are much more flexible now. What do you think? Any ideas?
https://github.com/plepe/openstreetmap-date-format/blob/v0.2.0/templates/fr.js

Also, I improved the [HOWTO](https://github.com/plepe/openstreetmap-date-format/blob/v0.2.0/HOWTO_CONTRIBUTE.md).

**Comment by james2432** [comment]
seems a lot more flexible as now you have the context if its a day/month/century/week etc. Not sure how other languages fair in this regard, but they probably will have exceptions/different rules from the Germanic languages

**Comment by plepe** [comment]
Yes, let's see :-)

**Pull request merged**
