### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by danieldegroot2**
Created Dutch translation. Unfortunately I have no experience doing lint.

One thing of note is that a month's name in the middle of a sentence does not get a capital letter. ie. "3 februari 2010".

### CODE REVIEW

**Comment by plepe** [comment]
Thanks for your contribution, it is highly appreciated!

There are a few issues though:
* in the file `test/nl.js`, you have to replace the `const locale = 'en'` by `const locale = 'nl'`.
* in the file `templates/nl.js`, line 58, `article` is unresolved. Shall this be `options.article`?
* when running `npm run test`, the code fails in line 13 with not equal strings: actual "3 februari 1901", expected "3 februari, 1901". There are even more errors after that.

Could you please solve these issues?

About linting: just run `npm run lint`, which will automatically solve some easy problems (e.g. formatting errors) and will report other problems with the code.

**Comment by danieldegroot2** [comment]
> in the file test/nl.js, you have to replace the const locale = 'en' by const locale = 'nl'.

Done in https://github.com/plepe/openstreetmap-date-format/pull/19/commits/6fc0fd145696ed5184e670e70e6582e8f48b1398

> in the file templates/nl.js, line 58, article is unresolved. Shall this be options.article?

Forgot to bring over the function `article` ( https://github.com/plepe/openstreetmap-date-format/pull/19/commits/5fc15aeab262045638d9867bd8422c2513142a56 ). I'm not sure about `options.article`, it's not present in the [french translation](https://github.com/danieldegroot2/openstreetmap-date-format/blob/6fc0fd145696ed5184e670e70e6582e8f48b1398/templates/fr.js#L72) (linking to the line where I got the main part from)

> when running npm run test, the code fails in line 13 with not equal strings: actual "3 februari 1901", expected "3 februari, 1901". There are even more errors after that.

We don't use any comma's in dates. I've removed the last remaining one in https://github.com/plepe/openstreetmap-date-format/pull/19/commits/21455bf7a3dea170ff08b8e9307fb01bedd0c7f5 .

> About linting: just run npm run lint, which will automatically solve some easy problems (e.g. formatting errors) and will report other problems with the code.

Sorry, I use the browser version.

**Comment by plepe** [comment]
There are still several problems when running the tests:

```
  1) Locale "nl"
       day:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ '3 feb. 1901'
- '3 feb 1901'
        ^
      + expected - actual

      -3 feb. 1901
      +3 feb 1901
      
      at Context.<anonymous> (test/nl.js:14:12)
      at process.processImmediate (node:internal/timers:471:21)

  2) Locale "nl"
       month:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'februari 1901'
- 'Februari 1901'
      + expected - actual

      -februari 1901
      +Februari 1901
      
      at Context.<anonymous> (test/nl.js:18:12)
      at process.processImmediate (node:internal/timers:471:21)

  3) Locale "nl"
       circa:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'ca. okt. 2010'
- 'ca. okt 2010'
          ^
      + expected - actual

      -ca. okt. 2010
      +ca. okt 2010
      
      at Context.<anonymous> (test/nl.js:43:12)
      at process.processImmediate (node:internal/timers:471:21)

  4) Locale "nl"
       pure:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'februari 1901'
- 'Februari 1901'
      + expected - actual

      -februari 1901
      +Februari 1901
      
      at Context.<anonymous> (test/nl.js:48:12)
      at process.processImmediate (node:internal/timers:471:21)

  5) Locale "nl"
       range:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'tussen le 19e eeuw en februari 1901'
- 'tussen de 19e eeuw en februari 1901'
          ^
      + expected - actual

      -tussen le 19e eeuw en februari 1901
      +tussen de 19e eeuw en februari 1901
      
      at Context.<anonymous> (test/nl.js:57:12)
      at process.processImmediate (node:internal/timers:471:21)
```

**Comment by danieldegroot2** [comment]
1) It is not required to add a dot to the abbreviation in the case of month names. In certain contexts, for example in diaries or on calendars where it's clear it concerns a date, the full stop is often omitted. This spelling is also correct.
(usage is somewhat 50/50 between articles)

2) > One thing of note is that a month's name in the middle of a sentence does not get a capital letter. ie. "3 februari 2010". 

(quoting my first post)

3) see 2.

4) see 1.

**Comment by plepe** [comment]
You are welcome to either change the code (templates/nl.js) or the test (test/nl.js). I can only merge your code, when the code creates the expected output (that you defined in test/nl.js). 

The code uses [momentjs](https://momentjs.com/) to format dates. If you are not happy with their output, you could either build the date strings yourself or request a change there.

I set up a very simple app, where you can develop and test your code:
https://openstreetbrowser.org/openstreetmap-date-format-dev/?lang=nl

On the left side you can edit all three files (select the one you want to change). On the right side you get the output of `npm run test` after clicking "Save and run tests".

**Comment by danieldegroot2** [comment]
I've changed both, so it should now pass all tests.
As for 2., they do not have it planned. Someone would need to manually change the strings somewhere. Capitalisation is not that big of an issue though, as long as it returns things in the right order.

Fyi; From looking at the website, it'll be fine unless we had
``moment().format('MMMM Do YYYY, h:mm:ss a')`` ;
which would return
> december 11de 2022, 5:01:04 pm

As far as I know we uncommonly use "11de december", but do not use the inverse notation "december 11de".

**Comment by plepe** [comment]
Awesome, thank you! I took the liberty to squash all the changes into a single commit - I hope, that's okay for you.

The contribution is already included in OpenStreetBrowser, as you can see here:
Screenshot 2022-12-11 at 22-38-40 OpenStreetBrowser

I'll create a news entry on the OpenStreetBrowser blog in the next days, maybe other contributors can be encouraged to create further translations.

**Pull request merged**
